### ISSUE TITLE
Title link to same language index

### ISSUE THREAD

**Issue by aguadopd** [sylvaindurand/multilingual-jekyll#3]
Hello! Thanks for your great contribution.

I noted that your title link is always pointing to the base index, not the one of the current language. In your hosted example, either while in *en* or in *fr*, the title is pointing to https://multilingual.sylvaindurand.org/

Is there any way to change it? Tried it with `<a class="site-title" href="{{ site.baseurl }}/{{ site.index[page.lang] }}/">{{ site.title[page.lang] }}</a>` but in my spanish case it is pointing to `http://localhost:4000/index_es.html/` while it should be `http://localhost:4000/index_es/` as it is generated with 
```
# Pages
index:
  en:
  es: index_es.html
```
in _config.yml

**Comment by sylvaindurand** [comment]
Well seen! I'll fix it.

In your case, you should use:

> index:
>   en: ""
>   es: "index_es/"

And:

> <a class="site-title" href="{{ site.baseurl }}/{{ site.index[page.lang] }}">{{ site.title[page.lang] }}</a>

**Comment by sylvaindurand** [comment]
Actually, my example works perfectly locally (jekyll 3.1.2) but doesn't work on GitHub... I'll try to figure out why later, or lazily waiting for GitHub to release a newer version of Jekyll...

**Comment by aguadopd** [comment]
Wonderful, the solution worked perfectly here. Hope it works when up online too! :D 
Thank you!

**Comment by sylvaindurand** [comment]
I don't know why it didn't work in the first place, I just had to rebuild and everything looks fine now. Thank you!
